/* AUTOGENERATED — 请勿手改。
 * 源：tools/arxiv/src/dates.js
 * 重新生成：python scripts/build-arxiv-core.py
 * 漂移检查：python scripts/build-arxiv-core.py --check（preflight 已含）
 */
var ArxivDates = (function () {
"use strict";

/**
 * 日期工具。
 *
 * arXiv 的 submittedDate 区间语法是 `[YYYYMMDDHHMM TO YYYYMMDDHHMM]`（GMT，闭区间、精确到分），
 * 而人习惯写 `2025-01-01`。这里做双向转换，并对「下界补 0000、上界补 2359」做显式约定——
 * 否则 `--from 2025-01-01 --to 2025-01-31` 会漏掉 1 月 31 日全天。
 */

const { ConfigError } = ArxivErrors;

/** 判断是否为合法 ISO 日期（YYYY / YYYY-MM / YYYY-MM-DD / 带时间）。 */
function isDateLike(s) {
  return /^\d{4}(-\d{2}(-\d{2}([T ]\d{2}:\d{2}(:\d{2})?)?)?)?$/.test(String(s || "").trim());
}

/**
 * 归一化为 arXiv 时间戳：`YYYYMMDDHHMM`（12 位）。
 * @param {string|Date|number} value
 * @param {"start"|"end"} [bound] 仅当输入粒度不足时用于补齐：start→0000，end→2359
 * @returns {string}
 */
function toArxivStamp(value, bound) {
  const b = bound === "end" ? "end" : "start";
  if (value == null || value === "") return "";
  if (value instanceof Date) {
    if (isNaN(value.getTime())) throw new ConfigError("无效的日期对象：" + String(value));
    return dateToStamp(value);
  }
  const s = String(value).trim();

  // 已是 12 位压缩格式：202501010000
  if (/^\d{12}$/.test(s)) return s;
  // 8 位：20250101
  if (/^\d{8}$/.test(s)) return s + (b === "end" ? "2359" : "0000");
  // 6 位：202501
  if (/^\d{6}$/.test(s)) return s + (b === "end" ? "312359" : "010000");
  // 4 位：2025
  if (/^\d{4}$/.test(s)) return s + (b === "end" ? "12312359" : "01010000");

  const m = s.match(/^(\d{4})-(\d{2})(?:-(\d{2}))?(?:[T ](\d{2}):(\d{2})(?::(\d{2}))?)?$/);
  if (!m) {
    throw new ConfigError("无法解析的日期：" + s, { hint: "支持 2025 / 2025-01 / 2025-01-31 / 2025-01-31T12:30" });
  }
  const [, y, mo, d, hh, mm] = m;
  const year = y;
  const month = mo;
  const day = d || (b === "end" ? "31" : "01");
  const hour = hh != null ? hh : (b === "end" ? "23" : "00");
  const minute = mm != null ? mm : (b === "end" ? "59" : "00");
  return year + month + day + hour + minute;
}

function dateToStamp(d) {
  const p = (n) => String(n).padStart(2, "0");
  return String(d.getUTCFullYear()) + p(d.getUTCMonth() + 1) + p(d.getUTCDate()) +
    p(d.getUTCHours()) + p(d.getUTCMinutes());
}

/** arXiv 时间戳（YYYYMMDDHHMM）→ Date（UTC）。非法输入返回 null。 */
function stampToDate(stamp) {
  const s = String(stamp || "");
  if (!/^\d{12}$/.test(s)) return null;
  const d = new Date(Date.UTC(
    Number(s.slice(0, 4)), Number(s.slice(4, 6)) - 1, Number(s.slice(6, 8)),
    Number(s.slice(8, 10)), Number(s.slice(10, 12))
  ));
  return isNaN(d.getTime()) ? null : d;
}

/**
 * 生成闭区间表达式：`submittedDate:[A TO B]`。
 *
 * ★ `--from` 单独给出时上界开区间（到 9999），即「自该时刻起」——
 * 早期实现把上界补成「同一天 2359」，于是 `--from 2026-09-13` 只返回当天结果，
 * 与命令行用户对 `--from` 的直觉（从这天开始往后）严重不符（实测才发现）。
 * 要表达「某一整天/整月」请显式给 `--to`。
 */
function rangeClause(field, from, to) {
  const f = String(field || "submittedDate");
  const a = from ? toArxivStamp(from, "start") : "";
  const b = to ? toArxivStamp(to, "end") : "";
  if (!a && !b) return "";
  const lo = a || "000101010000";
  const hi = b || "999912312359";
  return f + ":[" + lo + " TO " + hi + "]";
}

/** ISO 字符串 → 展示用 `YYYY-MM-DD`（容错）。 */
function dayOf(value) {
  const s = String(value || "");
  const m = s.match(/^(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : s;
}

/** ISO 字符串 → 展示用 `YYYY-MM-DD HH:mm`（本地时区，容错）。 */
function humanOf(value) {
  const s = String(value || "");
  if (!s) return "";
  const d = new Date(s);
  if (isNaN(d.getTime())) return s.slice(0, 16).replace("T", " ");
  const p = (n) => String(n).padStart(2, "0");
  return d.getFullYear() + "-" + p(d.getMonth() + 1) + "-" + p(d.getDate()) + " " + p(d.getHours()) + ":" + p(d.getMinutes());
}

/** 距今天数（负值表示未来）。 */
function daysAgo(value, nowMs) {
  const t = value instanceof Date ? value.getTime() : Date.parse(String(value));
  if (!isFinite(t)) return NaN;
  return ((nowMs == null ? Date.now() : nowMs) - t) / 86400000;
}

/** 按 bucket 分桶键：day→YYYY-MM-DD，month→YYYY-MM，year→YYYY。 */
function bucketKey(value, bucket) {
  const s = String(value || "");
  if (bucket === "year") return s.slice(0, 4);
  if (bucket === "month") return s.slice(0, 7);
  return s.slice(0, 10);
}

return { isDateLike, toArxivStamp, stampToDate, rangeClause, dayOf, humanOf, daysAgo, bucketKey, dateToStamp };
}());

