#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 tools/arxiv/src 的纯模块转成插件作用域模块（生成器）。

## 为什么需要它

`tools/arxiv/` 是零依赖的 Node 工具包（CLI + 库），但它**不能直接进 xpi**：
Zotero 插件跑在特权 JS 作用域里，没有 `require` / `module.exports`，也没有 Node 的
`fs` / `http` / `crypto`。

于是这里做一层**机械转换**：把「纯函数模块」（不碰 fs/http/crypto 的那些）改写成
`var ArxivXxx = (function () { ... })();` 的全局对象，放进 `chrome/content/scripts/arxiv/`。

**单一真源仍是 `tools/arxiv/src/`**：插件侧代码是生成物，改逻辑改源文件后重跑本脚本。
这样避免了「同一份解析逻辑在插件与 CLI 里各写一遍、然后慢慢漂移」——
这类漂移的典型后果是「CLI 里对、插件里错」，且两边测试都绿。

`--check` 模式只比对不写盘，用于 preflight 拦住「改了源却忘了重新生成」。

用法：
    python scripts/build-arxiv-core.py            # 生成
    python scripts/build-arxiv-core.py --check    # 只检查是否同步（不同步则非零退出）
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "tools", "arxiv", "src")
OUT_DIR = os.path.join(ROOT, "chrome", "content", "scripts", "arxiv")

# 生成物头部标记：写文件前必须确认目标文件含此标记（或不存在），
# 否则拒绝覆盖 —— 防止手写文件（如 arxiv-fetch.js）被同名生成物误伤。
AUTOGEN = "AUTOGENERATED"

# 白名单：只转「纯」模块（不 require Node 内置模块）。
# 顺序 = 依赖序（被依赖者在前），生成物加载顺序与此一致。
MODULES = [
    ("errors", "ArxivErrors", []),
    ("dates", "ArxivDates", ["errors"]),
    ("query", "ArxivQuery", ["errors", "dates"]),
    ("categories", "ArxivCategories", []),
    ("atom", "ArxivAtom", ["errors"]),
    ("analyze", "ArxivAnalyze", ["atom", "dates"]),
    ("rate-limiter", "ArxivRateLimiter", []),
]

GLOBAL_OF = dict((name, g) for name, g, _ in MODULES)

REQUIRE_RE = re.compile(
    r"""(?m)^[ \t]*(?:const|let|var)\s+(.+?)\s*=\s*require\(\s*["']\./([A-Za-z0-9_-]+)["']\s*\)\s*;""")
NODE_BUILTIN_RE = re.compile(r"""(?m)^[ \t]*(?:const|let|var)\s+.+?=\s*require\(\s*["']([^"']+)["']\s*\)""")


def die(msg):
    sys.stderr.write("✗ " + msg + "\n")
    return 1


def transform(src_path, mod_name, deps):
    """把一个 Node 模块源码转成插件作用域全局对象定义。"""
    raw = io.open(src_path, encoding="utf-8").read()

    # 1) 依赖必须都在白名单里（否则生成的代码会引用不存在的全局）
    for dep in deps:
        if dep not in GLOBAL_OF:
            raise ValueError("%s 依赖 ./%s，但它不在生成白名单里" % (mod_name, dep))

    # 2) 先把 ./xxx 的 require 换成全局引用
    def repl(m):
        target, dep = m.group(1).strip(), m.group(2)
        if dep not in GLOBAL_OF:
            raise ValueError("%s require(\"./%s\") 不在白名单" % (mod_name, dep))
        return "const %s = %s;" % (target, GLOBAL_OF[dep])

    body = REQUIRE_RE.sub(repl, raw)

    # 3) 任何残留的 require 都是 Node 内置（fs/http/crypto/os/path…）→ 不能进插件
    m = NODE_BUILTIN_RE.search(body)
    if m:
        raise ValueError("%s 仍依赖 Node 内置模块 %r，不在可移植白名单内" % (mod_name, m.group(1)))

    # 4) module.exports = {...}  →  return {...}
    # ⚠️ 必须连同 `=` 一起替换：只换 "module.exports" 会产出 `return = {...}` 这种语法错误
    # （生成器第一次跑就踩了，所以下面第 6 步强制跑一遍 node --check 兜底）。
    if "module.exports" not in body:
        raise ValueError("%s 没有 module.exports，无法确定导出面" % mod_name)
    body = re.sub(r"module\.exports\s*=", "return", body, count=1)

    # 5) 收尾自检：生成物里不允许出现插件作用域没有的标识
    for bad in ("require(", "module.exports", "process.", "__dirname", "__filename"):
        if bad in body:
            raise ValueError("%s 转换后仍含 %r（插件作用域不存在）" % (mod_name, bad))

    global_name = GLOBAL_OF[mod_name]
    header = (
        "/* %s — 请勿手改。\n"
        " * 源：tools/arxiv/src/%s.js\n"
        " * 重新生成：python scripts/build-arxiv-core.py\n"
        " * 漂移检查：python scripts/build-arxiv-core.py --check（preflight 已含）\n"
        " */\n" % (AUTOGEN, mod_name)
    )
    footer = "\n"
    out = (header
           + "var %s = (function () {\n" % global_name
           + body.rstrip() + "\n"
           + "}());\n" + footer)
    return out


def build():
    """返回 [(输出绝对路径, 文本)]，按依赖序。"""
    items = []
    for name, _global, deps in MODULES:
        src = os.path.join(SRC_DIR, name + ".js")
        if not os.path.exists(src):
            raise ValueError("源文件不存在：%s" % src)
        items.append((os.path.join(OUT_DIR, "arxiv-" + name + ".js"), transform(src, name, deps)))
    return items


def node_bin():
    """找 node（与 preflight 同一套候选顺序）。找不到返回 None，语法自检退化为跳过。"""
    import shutil
    cands = [
        os.environ.get("PP_NODE") or "",
        shutil.which("node") or "",
        r"C:\Users\Administrator\.workbuddy\binaries\node\versions\22.22.2-5\node.exe",
    ]
    return next((p for p in cands if p and os.path.exists(p)), None)


def syntax_check(text, label):
    """把生成结果写进临时文件跑 node --check。

    生成器是「代码生成代码」，一旦转错就是**整份文件语法错误**——
    而插件里 loadSubScript 失败只会写一行 boot 日志、功能静默降级，
    光靠实机很难第一时间发现。所以在写盘前先自检。
    """
    node = node_bin()
    if not node:
        return
    import subprocess
    import tempfile
    fd, tmp = tempfile.mkstemp(suffix=".js")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        p = subprocess.run([node, "--check", tmp], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if p.returncode != 0:
            raise ValueError("%s 生成结果语法错误：\n%s" % (label, p.stdout.decode("utf-8", "replace").strip()))
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def main(argv):
    check = "--check" in argv
    try:
        items = build()
        if not check:
            for path, text in items:
                syntax_check(text, os.path.basename(path))
    except ValueError as e:
        return die(str(e))
    except Exception as e:  # noqa: BLE001
        return die("生成失败：%s: %s" % (type(e).__name__, e))

    if check:
        drift = []
        for path, text in items:
            rel = os.path.relpath(path, ROOT)
            if not os.path.exists(path):
                drift.append("%s 缺失（跑 python scripts/build-arxiv-core.py）" % rel)
                continue
            cur = io.open(path, encoding="utf-8").read()
            if cur != text:
                drift.append("%s 与源不同步（改了 tools/arxiv/src 却忘了重新生成）" % rel)
        # 额外的生成物孤儿：目录里带 AUTOGEN 标记但不在清单里的文件
        expected = set(os.path.basename(p) for p, _ in items)
        if os.path.isdir(OUT_DIR):
            for fn in sorted(os.listdir(OUT_DIR)):
                if not fn.endswith(".js") or fn in expected:
                    continue
                head = io.open(os.path.join(OUT_DIR, fn), encoding="utf-8").read(400)
                if AUTOGEN in head:
                    drift.append("chrome/content/scripts/arxiv/%s 是已废弃的生成物（源模块已移除）" % fn)
        if drift:
            for d in drift:
                sys.stderr.write("✗ " + d + "\n")
            sys.stderr.write("\narXiv 核心生成物不同步：%d 处问题\n" % len(drift))
            return 1
        sys.stdout.write("OK  arXiv 核心生成物与 tools/arxiv/src 同步（%d 个模块）\n" % len(items))
        return 0

    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)
    written = []
    for path, text in items:
        # 安全闸：目标已存在且**不是**生成物 → 拒绝覆盖（保护手写文件）
        if os.path.exists(path):
            head = io.open(path, encoding="utf-8").read(400)
            if AUTOGEN not in head:
                return die("%s 已存在且不是生成物，拒绝覆盖（手写文件请改名）" % os.path.relpath(path, ROOT))
        old = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != text:
            io.open(path, "w", encoding="utf-8", newline="\n").write(text)
            written.append(os.path.relpath(path, ROOT))
    if written:
        sys.stdout.write("已生成 %d 个文件：\n" % len(written))
        for w in written:
            sys.stdout.write("  " + w + "\n")
    else:
        sys.stdout.write("已是最新（%d 个模块，无变化）\n" % len(items))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
